# Generated by Django 5.2.1 on 2025-06-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código de Descuento')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed_amount', 'Monto Fijo')], max_length=20, verbose_name='Tipo de Descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor del Descuento')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido Desde')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Válido Hasta')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Mínimo de Compra (subtotal productos)')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Límite de Usos Totales')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Veces Usado')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Máximo de Descuento (para porcentaje)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
