# Generated by Django 5.2.1 on 2025-06-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_discount_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Descuento Aplicado'),
        ),
    ]
