# docker-compose.yml
services:
  web:
    build: .
    command: gunicorn flow_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app # Para desarrollo local, en producción EasyPanel lo maneja diferente
    env_file:
      - .env
    dns: # Esto es bueno mantenerlo por si acaso
      - 8.8.8.8
    # Elimina o comenta la sección 'ports' para el despliegue con EasyPanel
    # ports:
    #   - "8000:8000"