# Generated by Django 5.2.1 on 2025-06-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tag')),
                ('slug', models.SlugField(blank=True, help_text='Versión amigable para URL del nombre del tag.', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(help_text='Identificador único para la URL (se genera automáticamente si se deja vacío).', max_length=270, unique=True)),
                ('date', models.DateTimeField(verbose_name='Fecha de Publicación')),
                ('author_name', models.CharField(max_length=150, verbose_name='Nombre del Autor')),
                ('excerpt', models.TextField(verbose_name='Resumen Corto')),
                ('content', models.TextField(verbose_name='Contenido Completo (HTML)')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen Principal')),
                ('image_alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Alternativo de Imagen Principal')),
                ('data_ai_hint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Palabras Clave para IA (Imagen)')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='¿Está Publicado?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_posts', to='blog.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Artículo del Blog',
                'verbose_name_plural': 'Artículos del Blog',
                'ordering': ['-date'],
            },
        ),
    ]
