# Generated by Django 5.2.1 on 2025-06-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_image_url_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='additional_image_urls',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs completas a imágenes adicionales. Ejemplo: ["url1", "url2"]', null=True, verbose_name='URLs de Imágenes Adicionales'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video_urls',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs a videos (YouTube, Vimeo, etc.). Ejemplo: ["url_video1", "url_video2"]', null=True, verbose_name='URLs de Videos'),
        ),
    ]
