# Generated by Django 5.2.1 on 2025-06-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_additional_image_urls_blogpost_video_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen Principal'),
        ),
    ]
