# Generated by Django 5.2.1 on 2025-05-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('slug', models.SlugField(help_text='Versión amigable para URL del nombre, usualmente en minúsculas y con guiones.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la Imagen')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
    ]
