# Generated by Django 5.2.1 on 2025-05-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_ai_hint_frontend',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Palabras Clave para Búsqueda IA'),
        ),
        migrations.AddField(
            model_name='product',
            name='difficulty_frontend',
            field=models.CharField(blank=True, help_text="Ej: 'Fácil', 'Medio', 'Avanzado'", max_length=50, null=True, verbose_name='Nivel de Dificultad'),
        ),
        migrations.AddField(
            model_name='product',
            name='harvest_time_frontend',
            field=models.CharField(blank=True, help_text="Ej: '7-12 días' o '1-2 semanas (después de colonización)'", max_length=50, null=True, verbose_name='Tiempo Estimado de Cosecha'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alt_frontend',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Alternativo de Imagen'),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time_frontend',
            field=models.TextField(blank=True, help_text='Descripción del proceso en casa del cliente si aplica (ej. para kits de colonización).', null=True, verbose_name='Tiempo de Espera/Proceso Cliente'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_frontend',
            field=models.FloatField(blank=True, null=True, verbose_name='Calificación Promedio'),
        ),
        migrations.AddField(
            model_name='product',
            name='status_frontend',
            field=models.CharField(blank=True, help_text="Ej: 'Listo para Fructificar (Cosecha Rápida)', 'Inicia Colonización en Casa (Ahorro)'", max_length=100, null=True, verbose_name='Estado para Frontend'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Peso del producto en GRAMOS. Esencial para cálculo de envío.', null=True, verbose_name='Peso (gramos)'),
        ),
    ]
