# Generated by Django 5.2.1 on 2025-06-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_data_ai_hint_frontend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_image_urls',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs completas a imágenes adicionales. Ejemplo: ["url1", "url2"]', null=True, verbose_name='URLs de Imágenes Adicionales'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_urls',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs a videos (YouTube, Vimeo, etc.). Ejemplo: ["url_video1", "url_video2"]', null=True, verbose_name='URLs de Videos'),
        ),
    ]
