# Generated by Django 5.2.1 on 2025-06-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_additional_image_urls_product_video_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen principal del producto.', null=True, upload_to='product_images/', verbose_name='Imagen del Producto'),
        ),
    ]
