# Generated by Django 5.2.1 on 2025-06-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de la imagen principal del producto.', max_length=500, null=True, verbose_name='URL de la Imagen'),
        ),
    ]
